### PR TITLE
in branch create cocktail ,recipe and profile pages and craete rating

### PR DESCRIPTION
**Pull request by AnasThaher**
this hashtag means the number of issues
- #8 
- #10 
- In this branch create cocktail, recipe, and profile pages, and create 'star-rating'

### CODE REVIEW

**Comment by nesmamanasra** [comment]
thank you anas, I check your task, all this is very well

**Comment by AnasThaher** [comment]
thanks nesma

**Review by nesmamanasra — APPROVED** [review]
good coding

**Review by safaafaqousah — APPROVED** [review]
good practice coding

**Pull request merged**
